
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.redhat.cxf;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-04-11T16:19:24.239-03:00
 * Generated source version: 3.1.11
 * 
 */

@javax.jws.WebService(
                      serviceName = "WSGerarProtocolo",
                      portName = "WSGerarProtocoloPort",
                      targetNamespace = "http://service.anbima.com.br/corp/protocolo",
                      wsdlLocation = "http://localhost:8080/SoapEndpoint/WSGerarProtocolo?wsdl",
                      endpointInterface = "com.redhat.cxf.WSGerarProtocolo")
                      
public class WSGerarProtocoloPortImpl implements WSGerarProtocolo {

    private static final Logger LOG = Logger.getLogger(WSGerarProtocoloPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.redhat.cxf.WSGerarProtocolo#gerarListaProtocolos(java.lang.String tipoProtocolo, java.lang.String origemProtocolo, int quantidade)*
     */
    public java.util.List<com.redhat.cxf.Protocolo> gerarListaProtocolos(java.lang.String tipoProtocolo, java.lang.String origemProtocolo, int quantidade) { 
        LOG.info("Executing operation gerarListaProtocolos");
        System.out.println(tipoProtocolo);
        System.out.println(origemProtocolo);
        System.out.println(quantidade);
        try {
            java.util.List<com.redhat.cxf.Protocolo> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.redhat.cxf.WSGerarProtocolo#gerarProtocolo(java.lang.String tipoProtocolo, java.lang.String origemProtocolo)*
     */
    public com.redhat.cxf.Protocolo gerarProtocolo(java.lang.String tipoProtocolo, java.lang.String origemProtocolo) { 
        LOG.info("Executing operation gerarProtocolo");
        System.out.println(tipoProtocolo);
        System.out.println(origemProtocolo);
        try {
            com.redhat.cxf.Protocolo _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
