package com.redhat.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-04-11T16:19:24.276-03:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://service.anbima.com.br/corp/protocolo", name = "WSGerarProtocolo")
@XmlSeeAlso({ObjectFactory.class})
public interface WSGerarProtocolo {

    @WebMethod(action = "http://service.anbima.com.br/corp/protocolo/ServicoProtocolo/gerarListaProtocolosRequest")
    @Action(input = "http://service.anbima.com.br/corp/protocolo/ServicoProtocolo/gerarListaProtocolosRequest", output = "http://service.anbima.com.br/corp/protocolo/ServicoProtocolo/gerarListaProtocolosResponse")
    @RequestWrapper(localName = "gerarListaProtocolos", targetNamespace = "http://service.anbima.com.br/corp/protocolo", className = "com.redhat.cxf.GerarListaProtocolos")
    @ResponseWrapper(localName = "gerarListaProtocolosResponse", targetNamespace = "http://service.anbima.com.br/corp/protocolo", className = "com.redhat.cxf.GerarListaProtocolosResponse")
    @WebResult(name = "listaProtocoloResponse", targetNamespace = "")
    public java.util.List<com.redhat.cxf.Protocolo> gerarListaProtocolos(
        @WebParam(name = "tipoProtocolo", targetNamespace = "")
        java.lang.String tipoProtocolo,
        @WebParam(name = "origemProtocolo", targetNamespace = "")
        java.lang.String origemProtocolo,
        @WebParam(name = "quantidade", targetNamespace = "")
        int quantidade
    );

    @WebMethod(action = "http://service.anbima.com.br/corp/protocolo/ServicoProtocolo/gerarProtocoloRequest")
    @Action(input = "http://service.anbima.com.br/corp/protocolo/ServicoProtocolo/gerarProtocoloRequest", output = "http://service.anbima.com.br/corp/protocolo/ServicoProtocolo/gerarProtocoloResponse")
    @RequestWrapper(localName = "gerarProtocolo", targetNamespace = "http://service.anbima.com.br/corp/protocolo", className = "com.redhat.cxf.GerarProtocolo")
    @ResponseWrapper(localName = "gerarProtocoloResponse", targetNamespace = "http://service.anbima.com.br/corp/protocolo", className = "com.redhat.cxf.GerarProtocoloResponse")
    @WebResult(name = "protocoloResponse", targetNamespace = "")
    public com.redhat.cxf.Protocolo gerarProtocolo(
        @WebParam(name = "tipoProtocolo", targetNamespace = "")
        java.lang.String tipoProtocolo,
        @WebParam(name = "origemProtocolo", targetNamespace = "")
        java.lang.String origemProtocolo
    );
}
