package com.redhat.cxf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-04-11T16:19:24.280-03:00
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "WSGerarProtocolo", 
                  wsdlLocation = "http://localhost:8080/SoapEndpoint/WSGerarProtocolo?wsdl",
                  targetNamespace = "http://service.anbima.com.br/corp/protocolo") 
public class WSGerarProtocolo_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.anbima.com.br/corp/protocolo", "WSGerarProtocolo");
    public final static QName WSGerarProtocoloPort = new QName("http://service.anbima.com.br/corp/protocolo", "WSGerarProtocoloPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/SoapEndpoint/WSGerarProtocolo?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WSGerarProtocolo_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/SoapEndpoint/WSGerarProtocolo?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WSGerarProtocolo_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSGerarProtocolo_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSGerarProtocolo_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public WSGerarProtocolo_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WSGerarProtocolo_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WSGerarProtocolo_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns WSGerarProtocolo
     */
    @WebEndpoint(name = "WSGerarProtocoloPort")
    public WSGerarProtocolo getWSGerarProtocoloPort() {
        return super.getPort(WSGerarProtocoloPort, WSGerarProtocolo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSGerarProtocolo
     */
    @WebEndpoint(name = "WSGerarProtocoloPort")
    public WSGerarProtocolo getWSGerarProtocoloPort(WebServiceFeature... features) {
        return super.getPort(WSGerarProtocoloPort, WSGerarProtocolo.class, features);
    }

}
